### ISSUE TITLE
Need to check licence of the bearsh/hid

### ISSUE THREAD

**Issue by seokho-son** [m-cmp/mc-iam-manager#4]
https://github.com/m-cmp/mc-iam-manager/blob/d1d1534acc549f0e9de324262273fa69b1bfa9c1/go.mod#L46C1-L46C42

(간접) 활용하고 있는, github.com/bearsh/hid 가 아파치2.0과 호환되지 않는 라이선스일 가능성이 높은 것 같습니다.

확인 부탁드립니다.

**Comment by raccoon-mh** [comment]
https://github.com/bearsh/hid/blob/master/LICENSE.md

okta idp 지원 모듈에 github.com/bearsh/hid 를 사용해서 USB 보안 모듈 인식 시키는 기능이 들어있어 삭제했습니다.
특별히 현재 진행중인 keycloak과 문제 없어보입니다.

https://github.com/m-cmp/mc-iam-manager/pull/5
